version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: npadmin
      MONGO_INITDB_ROOT_PASSWORD: npdevadmin
    ports:
      - '27018:27017'
    volumes:
      - ./.docker-data/.mongo-data:/data/db
  rabbitmq:
    image: rabbitmq:3.10.5-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./.docker-data/.rabbit-data:/var/lib/rabbitmq/
      - ./.docker-data/.rabbit-log:/var/log/rabbitmq
      - ./.rabbit-plugins:/etc/rabbitmq/enabled_plugins
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./.docker-data/.prometheus-data:/prometheus
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - '9000:3000'
    volumes:
      - ./.docker-data/.grafana-data:/var/lib/grafana"